# Generated by Django 5.0.6 on 2024-06-04 05:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('WAGON', 'Wagon'), ('HATCHBACK', 'Hatchback'), ('SPORTS', 'Sports'), ('TRUCK', 'Truck'), ('VAN', 'Van'), ('CONVERTIBLE', 'Convertible'), ('COUPE', 'Coupe'), ('MOTORCYCLE', 'Motorcycle'), ('MINIVAN', 'Minivan'), ('PICKUP', 'Pickup'), ('CROSSOVER', 'Crossover'), ('OTHER', 'Other')], default='SEDAN', max_length=12)),
                ('year', models.IntegerField(default=2023, validators=[django.core.validators.MinValueValidator(2015), django.core.validators.MaxValueValidator(2023)])),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('SOLD', 'Sold'), ('REPAIR', 'Repair'), ('IN_TRANSIT', 'In Transit'), ('HOLD', 'Hold')], default='AVAILABLE', max_length=10)),
                ('dateAdded', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('car_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.carmake')),
            ],
        ),
    ]
